PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/hmo#>

SELECT ?bill
WHERE {
  ?bill rdf:type :Bill .
  FILTER NOT EXISTS {
    ?bill :billGeneratedFor ?patient .
  }
}
