PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/hmo#>

SELECT ?treatment
WHERE {
  ?treatment rdf:type :Treatment .
  FILTER NOT EXISTS {
    ?treatment :treatedBy ?doctor .
  }
}
