PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/hmo#>

SELECT ?patient
WHERE {
  ?patient rdf:type :Patient .
  FILTER NOT EXISTS {
    ?patient :gender ?gender .
  }
}
